all: keytar.exe

CC=gcc
CXX=g++
COBJS=keytar.o hidapi/windows/hid.o
OBJS=$(COBJS) $(CPPOBJS)
CFLAGS=-Ihidapi/hidapi -c
LIBS= -lsetupapi
DLL_LDFLAGS = -mwindows -lsetupapi

keytar.exe: $(OBJS)
	g++ $^ $(LIBS) -o keytar

$(COBJS): %.o: %.c
	$(CC) $(CFLAGS) $< -o $@

clean:
	del keytar.o keytar.exe hidapi\windows\hid.o

.PHONY: clean
